### PR TITLE
feat(testretry): Add testretry command

### PR DESCRIPTION
**Pull request by nuclearcat**
Add command to retry some tests, in case test are flaky and we need to make sure it is not some glitch or hardware issue, by re-running the test.

### CODE REVIEW

**Comment by nuclearcat** [comment]
I will test PR and add some docs

**Comment by aliceinwire** [comment]
@nuclearcat any update on this?

**Comment by nuclearcat** [comment]
Sorry, i have personal situation, but i will restore work upcoming week.

**Review by aliceinwire — APPROVED** [review]

**Comment by aliceinwire** [comment]
thanks looks good

**Pull request merged**
